/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Rename Conversation */
        patch: operations["rename_conversation_api_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/conversations/{conversation_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Conversation */
        post: operations["archive_conversation_api_conversations__conversation_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inbox */
        get: operations["get_inbox_api_conversations__conversation_id__inbox_get"];
        put?: never;
        /** Enqueue Inbox */
        post: operations["enqueue_inbox_api_conversations__conversation_id__inbox_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/inbox/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Inbox */
        put: operations["reorder_inbox_api_conversations__conversation_id__inbox_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/inbox/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Inbox */
        delete: operations["remove_inbox_api_conversations__conversation_id__inbox__item_id__delete"];
        options?: never;
        head?: never;
        /** Edit Inbox */
        patch: operations["edit_inbox_api_conversations__conversation_id__inbox__item_id__patch"];
        trace?: never;
    };
    "/api/conversations/{conversation_id}/inbox/{item_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Inbox */
        post: operations["retry_inbox_api_conversations__conversation_id__inbox__item_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/inbox/{item_id}/steer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Steer Inbox */
        post: operations["steer_inbox_api_conversations__conversation_id__inbox__item_id__steer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Turns */
        get: operations["list_turns_api_conversations__conversation_id__turns_get"];
        put?: never;
        /** Start Turn */
        post: operations["start_turn_api_conversations__conversation_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/turns/{turn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Turn */
        get: operations["get_turn_api_conversations__conversation_id__turns__turn_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/turns/{turn_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Turn */
        post: operations["cancel_turn_api_conversations__conversation_id__turns__turn_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/turns/{turn_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turn Changes */
        get: operations["turn_changes_api_conversations__conversation_id__turns__turn_id__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/turns/{turn_id}/changes/{change_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File Change */
        get: operations["get_file_change_api_conversations__conversation_id__turns__turn_id__changes__change_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/turns/{turn_id}/changes/{change_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preview */
        get: operations["get_preview_api_conversations__conversation_id__turns__turn_id__changes__change_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/turns/{turn_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turn Events */
        get: operations["turn_events_api_conversations__conversation_id__turns__turn_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/turns/{turn_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Snapshot */
        get: operations["stream_snapshot_api_conversations__conversation_id__turns__turn_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Conversation */
        post: operations["unarchive_conversation_api_conversations__conversation_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Profile */
        put: operations["update_profile_api_profiles__profile_id__put"];
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_api_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Profile */
        post: operations["activate_profile_api_profiles__profile_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credential Info */
        get: operations["credential_info_api_profiles__profile_id__credential_get"];
        /** Credential Set */
        put: operations["credential_set_api_profiles__profile_id__credential_put"];
        post?: never;
        /** Credential Unset */
        delete: operations["credential_unset_api_profiles__profile_id__credential_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Snapshot */
        get: operations["run_snapshot_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Workspace Pick
         * @description Open the OS-native folder dialog on the server machine.
         *
         *     A sync endpoint: Starlette runs it in a threadpool, so the modal
         *     dialog never blocks the HTTP event loop (SSE keeps streaming).
         */
        post: operations["workspace_pick_api_workspace_pick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workspace Validate */
        post: operations["workspace_validate_api_workspace_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BootstrapDTO */
        BootstrapDTO: {
            /** Active Profile Id */
            active_profile_id?: string | null;
            capabilities: components["schemas"]["CapabilitiesDTO"];
            /** Profiles */
            profiles?: components["schemas"]["ProfileDTO"][];
            /** Provider Presets */
            provider_presets?: components["schemas"]["ProviderPresetDTO"][];
            run?: components["schemas"]["RunSnapshotDTO"] | null;
            /** Server Version */
            server_version: string;
            /** Session Token */
            session_token: string;
            /** State */
            state: string;
            ui: components["schemas"]["UIPreferencesDTO"];
        };
        /** CapabilitiesDTO */
        CapabilitiesDTO: {
            /** Char Budget */
            char_budget: number;
            /** Max Steps */
            max_steps: number;
            /** Wire Apis */
            wire_apis: string[];
        };
        /** ChangeSetDTO */
        ChangeSetDTO: {
            /** Additions */
            additions: number;
            /** Conversation Id */
            conversation_id: string;
            /** Coverage */
            coverage: string;
            /** Deletions */
            deletions: number;
            /** File Count */
            file_count: number;
            /** Files */
            files?: components["schemas"]["FileChangeDTO"][];
            /** Finalized At */
            finalized_at?: string | null;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Turn Id */
            turn_id: string;
        };
        /** ConversationCreateRequest */
        ConversationCreateRequest: {
            /** Profile Id */
            profile_id?: string | null;
            /** Title */
            title?: string | null;
            /** Workspace */
            workspace: string;
        };
        /** ConversationDTO */
        ConversationDTO: {
            /** Archived At */
            archived_at?: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Last Activity At */
            last_activity_at: string;
            latest_turn?: components["schemas"]["TurnDTO"] | null;
            /** Profile Id */
            profile_id?: string | null;
            /** State */
            state: string;
            /** Title */
            title: string;
            /** Title Source */
            title_source: string;
            /** Version */
            version: number;
            /** Workspace Key */
            workspace_key: string;
            /** Workspace Path */
            workspace_path: string;
        };
        /** ConversationPageDTO */
        ConversationPageDTO: {
            /** Items */
            items: components["schemas"]["ConversationDTO"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ConversationRenameRequest */
        ConversationRenameRequest: {
            /** Expected Version */
            expected_version: number;
            /** Title */
            title: string;
        };
        /** ConversationVersionRequest */
        ConversationVersionRequest: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /** Expected Version */
            expected_version: number;
        };
        /** CredentialInfoDTO */
        CredentialInfoDTO: {
            /** Configured */
            configured: boolean;
            /** Source */
            source: string | null;
            /** Writable */
            writable: boolean;
        };
        /** CredentialSetRequest */
        CredentialSetRequest: {
            /** Secret */
            secret: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
        };
        /** FileChangeDTO */
        FileChangeDTO: {
            /**
             * Additions
             * @default 0
             */
            additions: number;
            /** After Blob Id */
            after_blob_id?: string | null;
            /** After Sha */
            after_sha?: string | null;
            /** Before Blob Id */
            before_blob_id?: string | null;
            /** Before Sha */
            before_sha?: string | null;
            /**
             * Binary
             * @default false
             */
            binary: boolean;
            /** Change Type */
            change_type: string;
            /**
             * Deletions
             * @default 0
             */
            deletions: number;
            /** Id */
            id: string;
            /** Old Relative Path */
            old_relative_path?: string | null;
            /**
             * Preview Status
             * @default available
             */
            preview_status: string;
            /** Relative Path */
            relative_path: string;
            /** Source */
            source: string;
            /** Warnings */
            warnings?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthDTO */
        HealthDTO: {
            /** Run Id */
            run_id?: string | null;
            /** Run State */
            run_state: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** InboxEditRequest */
        InboxEditRequest: {
            /** Content */
            content?: string | null;
            /** Expected Version */
            expected_version: number;
            /** Mode */
            mode?: string | null;
        };
        /** InboxEnqueueRequest */
        InboxEnqueueRequest: {
            /** Content */
            content: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Mode
             * @default queue
             */
            mode: string;
            /** Reasoning Effort */
            reasoning_effort?: string | null;
        };
        /** InboxItemDTO */
        InboxItemDTO: {
            /** Bound Turn Id */
            bound_turn_id?: string | null;
            /** Claimed At */
            claimed_at?: string | null;
            /** Claimed Turn Id */
            claimed_turn_id?: string | null;
            /** Content */
            content: string;
            /** Conversation Id */
            conversation_id: string;
            /** Created At */
            created_at: string;
            /** Delivered At */
            delivered_at?: string | null;
            /** Id */
            id: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Last Error Code */
            last_error_code?: string | null;
            /** Position */
            position: number;
            /** Reasoning Effort */
            reasoning_effort?: string | null;
            /** Requested Mode */
            requested_mode: string;
            /** State */
            state: string;
            /** Updated At */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** InboxOrderRequest */
        InboxOrderRequest: {
            /** Expected Queue Version */
            expected_queue_version: number;
            /** Ordered Ids */
            ordered_ids: string[];
        };
        /** InboxSnapshotDTO */
        InboxSnapshotDTO: {
            /** Items */
            items?: components["schemas"]["InboxItemDTO"][];
            /** Queue Version */
            queue_version: number;
            /** Recent Events */
            recent_events?: {
                [key: string]: unknown;
            }[];
        };
        /** InboxVersionRequest */
        InboxVersionRequest: {
            /** Expected Version */
            expected_version: number;
        };
        /** PreviewDTO */
        PreviewDTO: {
            /**
             * Additions
             * @default 0
             */
            additions: number;
            /** After Sha */
            after_sha?: string | null;
            /** Before Sha */
            before_sha?: string | null;
            /**
             * Binary
             * @default false
             */
            binary: boolean;
            /** Change Id */
            change_id: string;
            /** Change Type */
            change_type: string;
            /** Current Sha */
            current_sha?: string | null;
            /**
             * Deletions
             * @default 0
             */
            deletions: number;
            /**
             * Diverged
             * @default false
             */
            diverged: boolean;
            error?: components["schemas"]["ErrorDetail"] | null;
            /** Lines */
            lines?: string[];
            /** Mode */
            mode: string;
            /** Relative Path */
            relative_path: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** ProfileDTO */
        ProfileDTO: {
            /** Base Url */
            base_url: string;
            credential: components["schemas"]["CredentialInfoDTO"];
            /** Credential Ref */
            credential_ref?: string | null;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Provider Id */
            provider_id: string;
            /** Reasoning Effort */
            reasoning_effort?: string | null;
            /**
             * Reasoning Mode
             * @default auto
             */
            reasoning_mode: string;
            /**
             * Show Reasoning
             * @default false
             */
            show_reasoning: boolean;
            /** Wire Api */
            wire_api: string;
        };
        /** ProfileInput */
        ProfileInput: {
            /** Base Url */
            base_url: string;
            /** Credential Ref */
            credential_ref?: string | null;
            /** Display Name */
            display_name: string;
            /** Model */
            model: string;
            /** Provider Id */
            provider_id: string;
            /** Reasoning Effort */
            reasoning_effort?: string | null;
            /** Reasoning Mode */
            reasoning_mode?: string | null;
            /** Show Reasoning */
            show_reasoning?: boolean | null;
            /** Wire Api */
            wire_api?: string | null;
        };
        /** ProviderPresetDTO */
        ProviderPresetDTO: {
            /** Default Base Url */
            default_base_url: string;
            /** Default Model */
            default_model: string;
            /** Display Name */
            display_name: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Provider Id */
            provider_id: string;
        };
        /** RunSnapshotDTO */
        RunSnapshotDTO: {
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            /** Events */
            events?: components["schemas"]["ToolEventDTO"][];
            /**
             * Events Retained From
             * @default 0
             */
            events_retained_from: number;
            /**
             * Events Total
             * @default 0
             */
            events_total: number;
            /** Final Text */
            final_text?: string | null;
            /** Finished At */
            finished_at?: number | null;
            last_verification?: components["schemas"]["VerificationDTO"] | null;
            /** Mutated Paths */
            mutated_paths?: string[];
            /** Phase */
            phase?: string | null;
            /**
             * Provider Attempt Count
             * @default 0
             */
            provider_attempt_count: number;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: number | null;
            /** State */
            state: string;
            /** Status */
            status?: string | null;
            /**
             * Step Count
             * @default 0
             */
            step_count: number;
            /** Stop Reason */
            stop_reason?: string | null;
            /** Task */
            task?: string | null;
            /**
             * Tool Call Count
             * @default 0
             */
            tool_call_count: number;
            /** Verification Status */
            verification_status?: string | null;
        };
        /** RunStartRequest */
        RunStartRequest: {
            /** Profile Id */
            profile_id?: string | null;
            /** Task */
            task: string;
            /** Workspace */
            workspace: string;
        };
        /** StreamCheckpointDTO */
        StreamCheckpointDTO: {
            /** Attempt */
            attempt: number;
            /** Channel */
            channel: string;
            /** Char Count */
            char_count: number;
            /** Event Seq */
            event_seq: number;
            /** Run Id */
            run_id: string;
            /** Text */
            text: string;
            /** Updated At */
            updated_at: string;
        };
        /** StreamSnapshotDTO */
        StreamSnapshotDTO: {
            /** Checkpoints */
            checkpoints?: components["schemas"]["StreamCheckpointDTO"][];
        };
        /**
         * ToolEventDTO
         * @description One public event with a monotonic id and a whitelisted payload.
         */
        ToolEventDTO: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Phase */
            phase: string;
            /** Step */
            step: number;
            /** Target */
            target?: string | null;
        };
        /** TurnCreateRequest */
        TurnCreateRequest: {
            /** Content */
            content: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Reasoning Effort */
            reasoning_effort?: string | null;
        };
        /** TurnDTO */
        TurnDTO: {
            /**
             * Active
             * @default false
             */
            active: boolean;
            /** Conversation Id */
            conversation_id: string;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Ordinal */
            ordinal: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** State */
            state: string;
            /** User Text */
            user_text: string;
        };
        /** TurnPageDTO */
        TurnPageDTO: {
            /** Items */
            items: components["schemas"]["TurnDTO"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** UIPreferencesDTO */
        UIPreferencesDTO: {
            /** Locale */
            locale?: string | null;
            /** Theme */
            theme?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerificationDTO */
        VerificationDTO: {
            /** Command */
            command?: string | null;
            /** Exit Code */
            exit_code?: number | null;
        };
        /**
         * WorkspacePickResponse
         * @description Result of the OS-native folder picker hosted by the local server.
         */
        WorkspacePickResponse: {
            /**
             * Cancelled
             * @default false
             */
            cancelled: boolean;
            error?: components["schemas"]["ErrorDetail"] | null;
            /** Path */
            path?: string | null;
        };
        /** WorkspaceValidateRequest */
        WorkspaceValidateRequest: {
            /** Path */
            path: string;
        };
        /** WorkspaceValidateResponse */
        WorkspaceValidateResponse: {
            error?: components["schemas"]["ErrorDetail"] | null;
            /** Resolved Path */
            resolved_path?: string | null;
            /** Valid */
            valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_api_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapDTO"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: {
                archived?: boolean | null;
                query?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_conversation_api_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_conversation_api_conversations__conversation_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inbox_api_conversations__conversation_id__inbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_inbox_api_conversations__conversation_id__inbox_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxEnqueueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_inbox_api_conversations__conversation_id__inbox_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_inbox_api_conversations__conversation_id__inbox__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_inbox_api_conversations__conversation_id__inbox__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_inbox_api_conversations__conversation_id__inbox__item_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    steer_inbox_api_conversations__conversation_id__inbox__item_id__steer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_turns_api_conversations__conversation_id__turns_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnPageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_turn_api_conversations__conversation_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_turn_api_conversations__conversation_id__turns__turn_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_turn_api_conversations__conversation_id__turns__turn_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turn_changes_api_conversations__conversation_id__turns__turn_id__changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_change_api_conversations__conversation_id__turns__turn_id__changes__change_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                turn_id: string;
                change_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileChangeDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preview_api_conversations__conversation_id__turns__turn_id__changes__change_id__preview_get: {
        parameters: {
            query?: {
                mode?: string;
            };
            header?: never;
            path: {
                conversation_id: string;
                turn_id: string;
                change_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turn_events_api_conversations__conversation_id__turns__turn_id__events_get: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolEventDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_snapshot_api_conversations__conversation_id__turns__turn_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_conversation_api_conversations__conversation_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDTO"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"][];
                };
            };
        };
    };
    create_profile_api_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_profile_api_profiles__profile_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    credential_info_api_profiles__profile_id__credential_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    credential_set_api_profiles__profile_id__credential_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    credential_unset_api_profiles__profile_id__credential_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfoDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_snapshot_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshotDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                last_event_id?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_pick_api_workspace_pick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePickResponse"];
                };
            };
        };
    };
    workspace_validate_api_workspace_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
